### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by bjorns163** [derlin/get-html#3]
fresh os install installed on debian bullseye 

testing app:
 `from get_html import HtmlRenderer`
`renderer = HtmlRenderer()`
`response = renderer.render(url= 'http://192.168.163.7/main-1.php')`

gives error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/get_html/html_renderer.py", line 142, in render
    response = self.loop.run_until_complete(self.async_render(url=url, **kwargs))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/get_html/html_renderer.py", line 93, in async_render
    browser = await self.async_browser
  File "/usr/local/lib/python3.9/dist-packages/get_html/html_renderer.py", line 55, in async_browser
    self.__browser = await pyppeteer.launch(
  File "/usr/local/lib/python3.9/dist-packages/pyppeteer/launcher.py", line 330, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.9/dist-packages/pyppeteer/launcher.py", line 152, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome'
`

installed:
` sudo apt-get install chromium chromium-driver gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

then this package
`pip3 install get-html`

I'm i missing something?

**Comment by derlin** [comment]
hello there! Which CPU architecture are you using? Are you running in a docker container?

**Comment by bjorns163** [comment]
No im running it on an orangepi. no dockers 

```
root@orangepizero2:~# lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1512.0000
CPU min MHz:         480.0000
BogoMIPS:            48.00
Flags:               fp asimd aes pmull sha1 sha2 crc32
```

apperantly pyppeteer on arm i get a x86-64 version installed [https://stackoverflow.com/a/66605044]

```
 file /root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome
/root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped
```

i followed the steps 

delete everything in the folder:  `/root/.local/share/pyppeteer/local-chromium/588429/chrome-linux`
create a link to correct verion of chrom browser on my system.  `ln -s /usr/bin/chromium-browser chrome`



now everything is working

**Comment by derlin** [comment]
Great! Sorry I forgot to answer. Yes, arm architecture explained part of the problem. Happy to know you figured it out!
